### ISSUE TITLE
applied to tweets

### ISSUE THREAD

**Issue by lucmichalski** [TheophileBlard/french-sentiment-analysis-with-bert#2]
Hi again,

Hope you are all well again !

Wanted to know if this sentiment analysis could be applied to tweets, and how ?

Have a great week-end !

Cheers,
Luc

**Comment by TheophileBlard** [comment]
Sure, you can do sentiment analysis on tweets ! 

You will need a large dataset of tweets in French language with their corresponding polarity. This is the most difficult part. As you can see [here](https://github.com/TheophileBlard/french-sentiment-analysis-with-bert/blob/master/allocine_dataset/README.md), I automated the annotating process for film reviews. Maybe you can also do it for tweets. You might want to take a look at [this projet](https://github.com/bfelbo/DeepMoji), where they use emojis to annotate tweets. 

You can also try to directly use my models, even if they are trained on movie reviews. As I show [here](https://github.com/TheophileBlard/french-sentiment-analysis-with-bert#generalizability), they can achieve state-of-the-art performances on other domains, such as books or music reviews.
But if you want to evaluate the performance of your models, you will still need data...

I close this issue for now, but feel free to re-open it if you have issues using your own dataset on my code.

**Comment by lucmichalski** [comment]
Just re-opening for a quick question about FlauBERT, have you tried it https://github.com/getalp/Flaubert ? Do you think that will work better than CamemBERT ?

**Comment by TheophileBlard** [comment]
> Just re-opening for a quick question about FlauBERT, have you tried it https://github.com/getalp/Flaubert ? Do you think that will work better than CamemBERT ?

I didn't try FlauBERT because there is no pre-trained model available in the [transformers](https://github.com/huggingface/transformers) library for Tensorflow (only PyTorch). However, I [evaluated](https://github.com/TheophileBlard/french-sentiment-analysis-with-bert#generalizability) my CamemBERT model on the [FLUE](https://github.com/getalp/Flaubert/tree/master/flue) benchmark, that was released alongside FlauBERT.

I advise you to read [CamemBERT](https://arxiv.org/pdf/1911.03894.pdf) and [FlauBERT](https://arxiv.org/pdf/1912.05372.pdf) papers. They are both short and easy to understand. Table 3 of the FlauBERT paper compare FlauBERT and CamemBERT performance on the FLUE text classification task (which is sentiment analysis). As you can see, FlauBERT (Base) is not better than CamemBERT. FlauBERT (Large) stands out, but it is very large (can't be loaded in a single GPU), and it's not available (yet) in the [transformers](https://github.com/huggingface/transformers) library.

![image](https://user-images.githubusercontent.com/37028092/77846017-59544100-71b3-11ea-84f6-85a3736d511a.png)

My only advise is to try both models on your data, and compare performance.
